apiVersion: apps/v1
kind: Deployment
metadata:
  name: stockzrs-metrics-service
  namespace: stockzrs-metrics-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stockzrs-metrics-service
  template:
    metadata:
      labels:
        app: stockzrs-metrics-service
    spec:
      nodeSelector:
        role: general
      containers:
      - name: stockzrs-metrics-service
        image: PLACEHOLDER_IMAGE
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        envFrom:
        - secretRef:
            name: stockzrs-metrics-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: stockzrs-metrics-service
  namespace: stockzrs-metrics-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: external
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
spec:
  selector:
    app: stockzrs-metrics-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer